### PR TITLE
change subcollections check

### PR DESCRIPTION
**Pull request by mkoura**
Subcollections list differs from version to version (and the hardcoded one is outdated).
EDIT:
~~In my opinion it's better to just try if whatever was passed is valid attribute/subcollection and skip the pre-check with hardcoded list altogether.~~
I added "subcollections" property that reads info from OPTIONS. When available, this subcollections info is also used for checking if the subcollection is valid for a given entity, as adviced by @abellotti

### CODE REVIEW

**Comment by abellotti** [comment]
As an alternative to the hardcoded list (maybe in future enhancement), you can also leverage OPTIONS /api/:collection, we now return the list of exposed subcollections for the :collection being handled.  This is what is done in the Ruby API Client gem, see https://github.com/ManageIQ/manageiq-api-client/pull/61.

**Comment by mkoura** [comment]
Thanks @abellotti , good idea, I'll change the PR accordingly.

**Comment by mkoura** [comment]
@cben @simon3z  any comments?

**Comment by cben** [comment]
LGTM

**Comment by simon3z** [comment]
@dkorn can you review?

**Comment by mkoura** [comment]
@simon3z @dkorn Any comments/suggestions? I'd like to have this PR merged, we (CFME QE) need this so we can start writing tests for subcollections that are not in current outdated list (like services/:id/vms).

**Pull request merged**
