### PR TITLE
Replace map with list comprehensions

### LINKED ISSUE #47: For py3 better compatibility `map` object should not return.
I found our calls returning `map` objects. user will face problems like 
`TypeError: 'map' object is not subscriptable` while they go for indexing.

As per me its should return `list` or `tuple`. return type should not be `map` object.

In `py2` `map` object allow indexing but not in `py3`. For workaround user need list compression which is not good.

Let me know maintainers thought on it.

### PR DESCRIPTION
**Pull request by mkoura**
fixes https://github.com/ManageIQ/manageiq-api-client-python/issues/47

### CODE REVIEW

**Comment by mkoura** [comment]
@cben please review

**Review by digitronik — APPROVED** [review]
LGTM :+1:

**Review by cben — APPROVED** [review]
LGTM

**Comment by izapolsk** [comment]
@cben, can we release client now ?

**Comment by mkoura** [comment]
@izapolsk I just released v0.5.1

**Comment by izapolsk** [comment]
@mkoura, brilliant. great thanks !

**Comment by digitronik** [comment]
@mkoura @cben thanks for quick release :+1:

**Pull request merged**
