### PR TITLE
Minimum required version 2.0.0

### PR DESCRIPTION
**Pull request by mfalesni**
I got rid of the sqlfilter and usage of is_in_series, fixing the errors when using find_by

### CODE REVIEW

**Comment by simon3z** [comment]
@dkorn please review
cc @abellotti

**Comment by abellotti** [comment]
this is fine, sqlfilter was only in 1.0 of the API, and was replaced with filter[] since 1.1.  Thanks!!

**Comment by simon3z** [comment]
@martinpovolny @abellotti when was first released version 2.0.0 of the API?

**Comment by abellotti** [comment]
May 2015, https://github.com/ManageIQ/manageiq_docs/blob/master/api/overview/versioning.adoc

**Pull request merged**
