### PR TITLE
Improved filter[] handling

### PR DESCRIPTION
**Pull request by mfalesni**
- Created a function that does ManageIQ-like escaping (Y U NO USE JSON)
- Changed the find_by to use that function instead of python repr
- Added a Q class working in a bit similar manner like Django's Q (though very simple so far)

### CODE REVIEW

**Comment by jarovo** [comment]
Note that for the newer naming_convention tests I don't need the unicode any more. I am converting to utf-8 on inputs and to unicode when outputting to selenium.

**Comment by mfalesni** [comment]
@Fryguy Thx, seems coming along nicely :)

**Comment by simon3z** [comment]
@dkorn please review

**Comment by jarovo** [comment]
Can we please merge this?

**Comment by simon3z** [comment]
> Can we please merge this?

@jaryn this is still marked as a `[WIP]`, @mfalesni is it finished?
@dkorn can you review?

**Comment by mfalesni** [comment]
Should be.

**Comment by jarovo** [comment]
Like!

**Pull request merged**
