### PR TITLE
Adding 'cloud_networks' subcollection

### PR DESCRIPTION
**Pull request by mkoura**
Adding 'cloud_networks' subcollection for cloud providers collection.

### CODE REVIEW

**Comment by simon3z** [comment]
@dkorn please review

**Comment by mkoura** [comment]
@simon3z @dkorn @cben Any issues with this PR?

What's your process for merging PRs? I'm wondering if it's doable for us (CFME QE) to replace our bundled REST API client without being blocked by waiting for you to merge changes that are necessary for our tests. Do you have any requests/ideas that could make reviewing and merging speedier?

**Comment by cben** [comment]
LGTM.

**Comment by simon3z** [comment]
@dkorn please review

**Comment by dkorn** [comment]
LGTM :+1:

**Pull request merged**
