### PR TITLE
Renaming the client as part of PyPI packaging effort

### PR DESCRIPTION
**Pull request by dkorn**
`manageiq-api-client-python` -> `manageiq-api-client`

### CODE REVIEW

**Comment by dkorn** [comment]
@cben @simon3z, should we also consider renaming the package itself? (or the other way around)
from `miqclient` to `manageiq_api_client`

cc @mfalesni

**Comment by cben** [comment]
Please fix commit message & PR description, should be "manageiq-api-client-python -> manageiq-api-client" with dashes not underscores.

If you do rename the package (so one would `import manageiq_api_client`),
also rename from dashes to underscores (so one would `pip install manageiq_api_client`),
as making the 2 equal is why I suggested this.
If you don't, keeping dashes is fine.
:+1: either way.

**Comment by simon3z** [comment]
cc @mfalesni

**Comment by simon3z** [comment]
I researched a little and I think I like `manageiq-client` for the name and `manageiq_client` for the package. Let's hear from @mfalesni and @cben as well.

**Comment by simon3z** [comment]
Ping anyone?

**Comment by cben** [comment]
\<bikeshedding color=forestgreen>
There will be 4 names involved:

1. git clone .../manageiq-api-client-python
2. dnf install python-manageiq-client
3. pip install manageiq-client
4. import manageiq_client

IMHO it'd be nice to have less *arbitrary* differences and get it down to say 3 names...
=> I vote changing the pypi package name to manageiq_client, matching the name you import.
(Python community is split on dashes vs underlines in package names with no clear winner)
I suppose the rpm package name becomes `python-manageiq_client`?  Not pretty but mechanically predictable...

git repo we could always rename, nothing much depends on it, let's leave it for now.
\</bikeshedding>

**Comment by simon3z** [comment]
> git clone .../manageiq-api-client-python
> dnf install python-manageiq-client
> pip install manageiq-client
> import manageiq_client

@cben names must be considered per ecosystem, not per-project.

` git clone manageiq-api-client-python`

Perfectly in line with the MangeIQ GitHub repository where you have to specify that it's the ManageIQ API Client in Python (there's also a Ruby one, etc.)

`dnf install python-manageiq-client`

Perfectly in line with Fedora and RH-based systems, the language binding first (python), then the name of the library (manageiq-client).

`pip install manageiq-client`

Perfectly in line with pip, no need to specify that it is in python (pip is for python packages to begin with), it is just the ManageIQ Client.

`import manageiq_client`

Perfectly in line with Python where the dash `-` is a minus sign and it cannot be used in packages. By default all packages that have a dash in the names change that to an underscore.

**Comment by cben** [comment]
Good points.  :+1:

**Comment by dkorn** [comment]
@simon3z are you OK with the change? 
notice I also renamed the directory from miqclient to manageiq_client, as well as renaming the module from api.py to manageiq_client.py

**Comment by simon3z** [comment]
I want to instantiate the client as:

```python
from manageiq_client.api import ManageIQClient
```

**Comment by dkorn** [comment]
@simon3z done

**Comment by simon3z** [comment]
@mfalesni any comment/feedback on this PR?

LGTM :+1:

**Comment by mfalesni** [comment]
@simon3z I am no longer participating in the client repo here, but I guess it is okay since we still use our older bundled client. There is a PR in our tests that should point stuff to the new repo so I will throw that at the person responsible for REST testing.

**Comment by simon3z** [comment]
> @simon3z I am no longer participating in the client repo here, but I guess it is okay since we still use our older bundled client. There is a PR in our tests that should point stuff to the new repo so I will throw that at the person responsible for REST testing.

@mfalesni can you cc here the relevant person?

**Comment by mfalesni** [comment]
@mkoura ^^

**Pull request merged**
