### PR TITLE
fix api_version

### PR DESCRIPTION
**Pull request by mkoura**
The ``.api_version`` is broken ATM.

### CODE REVIEW

**Comment by simon3z** [comment]
@cben can you review?

**Review by cben — APPROVED** [review]
Oops, I've ignored this because of the merge conflict.  LGTM.

I'll admit again that I'm insufficiently responsive on PRs in this repo.  (A) please nag me more :wink: (B) I think Martin should be a co-maintainer (C) this repo could use more reviewers...

**Comment by mkoura** [comment]
Thanks for review @cben, I rebased the PR and it's now ready to be merged. The test failure will be resolved by PR https://github.com/ManageIQ/manageiq-api-client-python/pull/32

**Comment by simon3z** [comment]
> Thanks for review @cben, I rebased the PR and it's now ready to be merged. The test failure will be resolved by PR #32

OK, FYI I'll be waiting for #32 to be approved before looking at this one.

**Pull request merged**
